spring:
  profiles: dev-remote
  include: default  
  datasource:
    url: jdbc:mysql://localhost:3306/app_dev
    username: root
    password: 1234
    platform: mysql
    initialize: true
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect