demo-mysql:
  image: mysql:latest
  environment:
    - MYSQL_ROOT_PASSWORD=p4SSW0rd
    - MYSQL_DATABASE=demo
    - MYSQL_USER=dbuser
    - MYSQL_PASSWORD=dbp4ss

app-app:
  image: app/app-app
  links:
    - demo-mysql:mysql
  ports:
    - 8080:8080
